### ISSUE TITLE
関連付けしてもファイルをキチンと開いてくれないんだけど・・・

### ISSUE THREAD

**Issue by YSRKEN** [hibara/MarkDownSharpEditor#11]
タイトルの如く。関連付けの後、拡張子mdのファイルをダブルクリックしてもファイルを開いて表示してくれません(D&Dなどが必要です)。
バージョンは1.1.4.0。

**Comment by alg0002** [comment]
パスに半角スペースを含むファイルはうまく開けないみたいですね。
とりあえずレジストリエディタで
HKEY_CLASSES_ROOT\MarkDown#Editor\shell\open\command
の(既定)のデータを
"(MarkDown#Editorのインストール先)\MarkDownSharpEditor.exe" %1
↓
"(MarkDown#Editorのインストール先)\MarkDownSharpEditor.exe" "%1"
のように、%1をダブルクォーテーションで括れば、
ダブルクリックで開けるようになりました。

**Comment by alg0002** [comment]
MrkSetup / Program.cs
の62行目を

``` diff
            //実行するコマンドライン
-           string CommandLine = "\"" + MarkDownSharpEditorPath + "\" %1";
+           string CommandLine = "\"" + MarkDownSharpEditorPath + "\" \"%1\"";
```

こんな感じに修正ですかね？（未検証）

**Comment by YSRKEN** [comment]
修正ありがとうございます。

**Comment by hibara** [comment]
ご報告ありがとうございます。

また、alg0002さん、フォローありがとうございます。！
毎度のことながら助かります。。。。

これまたへっぽこな記述をしておりました。
おっしゃるとおり、該当の箇所を修正することで対処できました。

これも次版にて修正・反映予定です。
