### ISSUE TITLE
「ブラウザプレビューまでの間隔」

### ISSUE THREAD

**Issue by YSRKEN** [hibara/MarkDownSharpEditor#12]
※報告は事例ごとに分けたほうがいいと思ったので分割しています。

オプション→全般→ブラウザプレビューまでの間隔の項目が、コンボボックスかと思ったらある時はインプットボックスになってしまうというバグがあります。
面倒なことに、コンボボックス時に「0.1秒」等設定していても、インプットボックス時には「100秒」になっていたりするのです。
バージョンは1.1.4.0。

**Comment by hibara** [comment]
ご指摘ありがとうございます。
おっしゃりとおり、現象は確認しました。

というより、実は、もともとデバッグ用に仕込んでいたものでして・・・。その意図は、ブラウザの応答時間を見ながら微妙に調整するという、試験的な意味合いで入れていた仕様です。

ただ、リリースしてずいぶんと経つ今では意味合いが薄くなってしまっているかもしれませんね。

ですので、今後はコンボボックスに統一しようと思います。

次版で修正予定です。
