### ISSUE TITLE
「全般(&R)」等の表示について

### ISSUE THREAD

**Issue by YSRKEN** [hibara/MarkDownSharpEditor#13]
※報告は事例ごとに分けたほうがいいと思ったので分割しています。

些細な事ですが、オプション中のタブが「&R」等と＆付きで書かれているのは仕様ですか？
ひょっとして下線表示したかったのでは？
(でもメモ帳等を見る限り、別に下線表示なんて必要ないのでは)
バージョンは1.1.4.0。

**Comment by hibara** [comment]
これまたご報告感謝です。

これは気づきませんでした・・・Windowsソフトを古くから開発していると、ニーモニックキー（altショートカットキー）を指定するのが脊髄反射みたいな感じになっていて、そのまま&を入力して、確認もしておりませんでした。。。

TabControlではショートカットキーを指定できないんですかね・・・C#に慣れていないので謎です。

ただ、Ctrl+Tabで各タブは切り替えていけるので、今では一発ショートカットキーの意味合いも薄れてきているのかもしれませんね。

というわけで、次版では「R」などの文字を削って、修正対応します。

**Comment by alg0002** [comment]
TabPageの場合、&Rなどとすればショートカットキーとしては機能するんですけど、”下線付きのR”とは表示されないのですよね…。
Button等ならちゃんと下線付きで表示されるのに。

どうしても下線付きで表示したい場合は、オーナードローするしかないようです。
http://dotnetrix.co.uk/tabcontrol.htm#tip9
そこまでしなくてもいいのでは、という気はします。

**Comment by hibara** [comment]
alg0002さん、コメントありがとうございます。

そうなんですか・・・ショートカットキーとしては機能するんですね。なんか、実に中途半端な機能ですね。
マイクロソフトは将来的にはニーモックキーを無くしたいのかなあ、と思ったりもして。

まあ、おっしゃるとおり、オーナードローするほどでもないので、アンパサンド（&）は無くて、そのまま文字表示することにしました。
