### ISSUE TITLE
Markdown Extraの機能の実装予定は？

### ISSUE THREAD

**Issue by YSRKEN** [hibara/MarkDownSharpEditor#14]
これはただの要望です。表とかもMarkdown表記できれば、それはとっても嬉しいなって。

**Comment by hibara** [comment]
ご要望もありがとうございます！

実はこれ、僕も最近チラッと脳裏をよぎっていたんですよね・・・
次版とか、直近ではムリですが、将来的に入れる方向で考えたいと思います。

milestoneは設定されませんが、一応このIssueはOpenのままにしておきます。
対応されるか、あるいは、実装が難しくて断念するかのどちらかまで(笑)。

**Comment by harupong** [comment]
Markdown Extraが導入されると聞いて飛んできました≡≡≡≡≡≡≡≡≡≡c⌒っﾟДﾟ)っ

オープンソースのMarkdown Extra対応C#なパーサーが出てるとか何とか...ﾁﾗﾁﾗｯ
[Topten Software](http://www.toptensoftware.com/markdowndeep/)

**Comment by hibara** [comment]
そうなんですよ。これ良いですよね。

最初はパーサーを独自に・・・とか、かなり身の丈超えのこと考えていたのですが、実はもうそんなパーサーも出てるかもと、GitHub界隈含めて探していたら、ご指摘のものに辿り着きました。実装も簡単そうですしね。
次版に向けて、ちょっと実験をしてみます。

ただ、エディタ側のシンタックスハイライターを実現するための正規表現パズルに手こずりそうな(笑)。
誰か正規表現を手伝ってくださる方、募集！　絶賛プルリクエストお待ちしています(笑)。

こっちがうまく行ったら、次版以降で搭載します。

なので、マイルストーンはやや遠めに設定しておきました。

**Comment by hibara** [comment]
長らくお待たせしておりましたが、とりあえず、MarkdownDeepを使って、次版（ver.1.2.0.0）で対応予定です。
本日付でGithub上にあがっているソースではすでに対応済みですが、もう少しテストしたいので、正式リリースはもうまだになります。テキストエディター側のシンタックスハイライターが、やや難有りって感じでしょうか。正規表現は難しいですね。
