### ISSUE TITLE
HTMLに変数定義リンクが反映されないようです

### ISSUE THREAD

**Issue by Meganezaru** [hibara/MarkDownSharpEditor#15]
”[hogehoge]:http://www.hoge.com” のように記載した場合、本文中の[hogehoge]にリンクがつかないようです。

**Comment by hibara** [comment]
確認してみました。

見たところ、ブラケット・コロン "]:" の後に、半角スペースが入っていないように見えますが、そこはどうでしょうか？　

Markdown記法の「リンク」については、以下を参照してみてください。
http://blog.2310.net/archives/6#links

ちなみに、以下の二行のように記述したら、きちんとリンクが現れました。
MarkDown#Editorにコピペして、確認してみてください。↓

```
This is [example][hogehoge] reference-style link.
[hogehoge]: http://www.hoge.com "Optional Title Here"
```

**Comment by Meganezaru** [comment]
ゴメンナサイ・・・おっしゃるとおりでした、自分の認識が甘かったんですね・・・

別のアプリで、反映されてたので、スペースが必要なことに気づいてませんでした・・・
お騒がせ、申し訳ないです。

スペースが無いときは、そのまま本文として表示されると、間違いに気づきやすいかもしれないですね。些細なことですが・・・

**Comment by hibara** [comment]
そうですか。とりあえず良かったです。

「スペースが無いときはそのまま本文で表示される・・・」って意外と良い仕様かも・・・と、一瞬思いましたが、それやっちゃうと「ブラウザー」としてのプレビューの意味ねーと、思い直したり(笑)。

あるとするなら、エディタ側で、反映されてないもののシンタックスハイライター表示を分けるとか、いいかもしれませんね。ちょっと考えてみます（実装するかは別にして）。

では今後ともよろしくお願いいたします。
