### ISSUE TITLE
ver1.1.5.0にてオプション画面を開きOKボタンを押すと例外を示すダイアログが発生する

### ISSUE THREAD

**Issue by kuramiya** [hibara/MarkDownSharpEditor#18]
環境はWindows7 64bit Professionalです。

ver1.1.5.0にてオプション画面を開きOKボタンを押すと例外を示すダイアログが発生します。
継続ボタンでアプリは継続して使用可能なようです。

以下、例外ダイアログのメッセージ

System.ArgumentOutOfRangeException: 値 '0' は 'Interval' に対して有効な値ではありません。Interval は 0 より大きくなければいけません。
パラメーター名: Interval
   場所 System.Windows.Forms.Timer.set_Interval(Int32 value)
   場所 MarkDownSharpEditor.Form1.menuOption_Click(Object sender, EventArgs e)
   場所 System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   場所 System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   場所 System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   場所 System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   場所 System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   場所 System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   場所 System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   場所 System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   場所 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   場所 System.Windows.Forms.Control.WndProc(Message& m)
   場所 System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   場所 System.Windows.Forms.ToolStrip.WndProc(Message& m)
   場所 System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   場所 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   場所 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   場所 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by hibara** [comment]
現象をこちらでも確認しました。
次版では修正されています（現在GitHubに上がっているソースでは対処済みです）。
