### ISSUE TITLE
PHP Markdown Extra 仕様日本語訳

### ISSUE THREAD

**Issue by harupong** [hibara/MarkDownSharpEditor#20]
hibaraさんがブログで公開された[PHP Markdown Extra仕様の全訳](http://hibara.org/blog/2013/03/11/php-markdown-extra-jp/)ですが､原稿をGitHubにあげていただくことは可能でしょうか？

先日メールでお知らせした修正事項以外にも何点か修正したメモが手元にありますので､原稿(Markdownファイル？)を直接GitHub上で修正できれば､と思っています｡

**Comment by hibara** [comment]
すみません、ちょっとゴタゴタしておりまして、、、メールをいただいていたのをすっかり忘れておりました。
遅ればせながら、Gistの方に上げてみました。よろしければ修正・加筆等お願いできればと思います。

https://gist.github.com/hibara/5661760

よろしくお願いいたします。

**Comment by harupong** [comment]
早速ありがとうございます｡これからは､何かあればGitHub issuesの方に登録するようにしますね :smile:
