### ISSUE TITLE
インストール時の言語指定が無視されてしまう(上書きインストール時)

### ISSUE THREAD

**Issue by harupong** [hibara/MarkDownSharpEditor#21]
乱暴なことをしているのでアレですが､

1) Ver1.1.5.0をアンインストールせずに､そのままVer1.2.0.0を同じパスにインストール
2) インストール時に言語設定を｢日本語｣にする
3) Ver1.2.0.0の初回起動時に言語が｢English｣になってしまう

ご参考まで｡

OS: Windows7 Pro(32bit)

**Comment by hibara** [comment]
基本的に他のアプリケーションでもあるとおり、それはインストーラだけの言語設定であって、そのままインストールされたアプリケーションまで言語設定が反映されるわけではありません。

とはいえ、これって直感的に「？？」となるのは確かですね。。。なので、インストーラの挙動含め、意図した動作になるように改良し、次版（ver.1.2.3.0）で反映します。

ご指摘ありがとうございます！
