### ISSUE TITLE
ソースコードのインデント文字が統一されていない

### ISSUE THREAD

**Issue by Yasami** [hibara/MarkDownSharpEditor#23]
TABとスペース2文字が混在しているようです。
5月26日のコミット（8f76b9dfdf8bab8942b1af404bf89a34dc1a6966）からでしょうか。
その他のスタイル統一のためにも、一度Visual Studioのコードフォーマッタを適用しただけのコミットを入れていただけると助かります。
（編集->詳細->ドキュメントのフォーマット）

こちらでフォーマットしてPull requestしてもよかったのですが、TABとスペースのどちらに寄せたいのかわからなかったので、お任せすることにしました。

詳しく調べていないのですが、改行コードも混在しているような気がします。
こちらもあわせて統一していただけると、差分比較が楽になってうれしいです。

**Comment by hibara** [comment]
コメントありがとうございます。
Visual Studioにコードフォーマッタなんて機能があるんですね。
知りませんでした。

さっそくご指摘のとおり、ほとんどのソースコードのインデントを統一してコミットしてみました。
