### ISSUE TITLE
既存の .md ファイルを開いて、何も変更せずに保存すると 開いた .md ファイルが削除されるバグ。

### ISSUE THREAD

**Issue by kkato233** [hibara/MarkDownSharpEditor#28]
var 1.2.2.0 を使っています。

「ファイル」メニューの「開く」を使って .md ファイルを開くと タイトルバーは

`(無題) - Markdown#Editor`

という表示になり、その状態でプログラムを終了すると 開いたはずの .md ファイルが
勝手に削除されてしまいます。

OpenFile 関数で _fNoTitle に設定する値に問題があるようです。

**Comment by hibara** [comment]
修正ありがとうございました！
