### ISSUE TITLE
エディターの背景色設定

### ISSUE THREAD

**Issue by harupong** [hibara/MarkDownSharpEditor#5]
エディター部分の色設定をSolarizedにしたいな､とポチポチやっていたのですが､終わりに近づいたところで｢あれ､エディター部分そのものの背景色を設定する項目がないぞ｣と気付きました．．．

![ScreenClip](https://f.cloud.github.com/assets/204623/105683/80cb4e12-69bf-11e2-97a8-eed5f3ab98c9.png)  
↑コメント部やリンク部などには背景色があるが､空行やテキスト部は白背景のまま｡

設定項目の追加いただけないでしょうか？

**Comment by alg0002** [comment]
設定ファイル
（C:\Users[ユーザー名]\AppData\Roaming\MarkDownSharpEditor\settings.config　など）
に項目がちゃんとあるようなので、設定画面でそこを変えられるようにすればよさそうですね。

上記設定ファイルの

``` xml
 <BackColor_MainText>-1</BackColor_MainText>
```

このあたりを適当な値に変えれば、とりあえず背景色を変えられるみたいです。
（ご存じでしたらすみません）
バージョンアップまではここを変更して間に合わせる、という方法もあります。

**Comment by harupong** [comment]
おお､こんなところに設定項目がっ！@alg0002さんありがとうございます｡
とりあえずここを変更して間に合わせてみました｡

カラースキーム設定を共有できるよう､colorscheme.config的なものに分離できるとよいですねぇ

**Comment by hibara** [comment]
harupongさん、alg0002さん、コメントありがとうございます。

設定ファイルに値があって、動作設定パネルにその設定項目がないのは、僕が単純に実装し忘れていたという・・・はい、凡ミスです。すみません。

次版で修正し、項目を追加します。

**Comment by harupong** [comment]
早速の対応ありがとうございました。新バージョンで修正確認しました！！
