### ISSUE TITLE
起動時に無題[nnnn].mdが生成される

### ISSUE THREAD

**Issue by harupong** [hibara/MarkDownSharpEditor#6]
オプション - 前に編集していたファイルを起動時に自動で開く

のチェックを外した状態でMarkDown#Editorを起動するたびに、無題[nnnn].md（0001～）が以下のディレクトリに生成されます。

C:\Users[ユーザー名]\AppData\Roaming\MarkDownSharpEditor　

これは仕様でしょうか？

MarkDown#Editor Version 1.1.4.0

**Comment by hibara** [comment]
ご報告ありがとうございます。仕様というか・・・バグです。すみません。

プレビューする関係で、どうしても「無題」編集のときにファイルの実体が必要だったため、テンポラリファイルとして生成するのですが、それが意図せずに残ってしまっていたようです。

やはり「無題」ファイルをテンポラリファイルとはいえ、ローカルに保存しておくのは、そもそも変な仕様ですので、根本から仕様を見直して、次版で改良入れたりと思います。

基本的にファイルが保存されるまでは、文字通り実体のない無題のまま編集して、そのままブラウザープレビューに反映する仕様にします。

次版で対応予定です。

**Comment by harupong** [comment]
確認ありがとうございます｡そういうことだったんですね｡仕様見直しになってしまったようで､申し訳ないです｡

とはいえ､テンポラリファイルに実体があると､無題状態でのファイル保存の挙動がNotepadやWordと異なってしまうので､ここは揃えるほうがいいように思います｡
- Notepadなどの場合:ソフト起動→無題状態で編集する→上書き保存しようとする→実体がないので｢名前を付けて保存｣ダイアログが呼ばれる
- Makdown#Editorの場合:ソフト起動→無題状態で編集する→上書き保存しようとする→実体があるのでそのまま 無題[nnnn].md に上書きしてしまう

引き続きよろしくお願いいたします｡
