### ISSUE TITLE
(無題) 状態でのHTMLプレビュー更新がエラーになる

### ISSUE THREAD

**Issue by harupong** [hibara/MarkDownSharpEditor#7]
MarkDown#Editor起動後[新しいファイル]を選択すると(無題)というバッファ（？）を開いているような状態になりますが、この状態でプレビュー画面を更新するとエラーになります。自動更新を有効にしていると、エラーウィンドウから[Continue]を選択して抜けてもほどなくしてまたエラーになります。

MarkDown#Editor 1.1.4.0

以下にエラー内容を貼り付けておきます。
Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.

Object reference not set to an instance of an object.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at MarkDownSharpEditor.Form1.PreviewToBrowser()
   at MarkDownSharpEditor.Form1.menuViewRefresh_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripMenuItem.ProcessCmdKey(Message& m, Keys keyData)
   at System.Windows.Forms.ToolStripManager.ProcessShortcut(Message& m, Keys shortcut)
   at System.Windows.Forms.ToolStripManager.ProcessCmdKey(Message& m, Keys keyData)
   at System.Windows.Forms.Form.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.TextBoxBase.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.RichTextBox.ProcessCmdKey(Message& m, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 (RTMRel.030319-0100)
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

MarkDownSharpEditor
    Assembly Version: 1.1.4.0
    Win32 Version: 1.1.4.0
##     CodeBase: file:///C:/Program%20Files%20(x86)/MarkDownSharpEditor/MarkDownSharpEditor.exe

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 (RTMRel.030319-0100)
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

edhtqt25
    Assembly Version: 1.1.4.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 (RTMRel.030319-0100)
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll

System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by hibara** [comment]
ご報告ありがとうございます。こちらでも現象を確認しました。

「無題」編集状態にして、スクロールさせようとすると、その不具合が発生するようです。

ブラウザプレビューする際に、スクロール位置の保存を行って、その位置を同期しているのですが、そこがバグっていたようです。

次版で修正対応予定です。

**Comment by harupong** [comment]
ご確認ありがとうございます｡修正よろしくお願いいたします｡

追伸:
30歳過ぎて遅きに失する感満載ですが､プログラミングの勉強を始めました｡artonさんという方が書かれた入門書でC#を勉強中です｡初心者ゆえ2歩進んで3歩下がってるような進捗ですが､いずれはPull request送れるよう頑張りたいと思います｡

**Comment by hibara** [comment]
ｳﾊﾊﾊ・・・僕なんて三十後半からの手習いですよ(笑)。
会社のとある「プロ」のプログラマーからは、「ようやく中級レベルですかね」と言われました(笑)。

まあ、お互いゆっくり行きましょう。十数年前に比べれば、書籍とか、ネットとか、情報はたくさん転がっているので、とても学びやすい環境と言えます。学習速度もはやいし、楽しさも大きいです。

なにか疑問点があれば、「中級」の僕からもアドバイスさせていただきます(笑)。
その際はお気軽にメールください。あと、プルリクエストもお待ち申し上げます。

では今後ともよろしくお願いいたします。

**Comment by harupong** [comment]
おお､それは心強い｡確かに学びやすい環境揃っていますね｡開発環境はとっても賢いし､Outputが手早く得られる感は勉強していて楽しいです｡で､現状ですが､
1. ひとまずMarkDown#Editorのソースをダウンロード
2. Visual Studio 2012でForm1.csのデザイナーが開けない
3. Visual Studio 2010をインストール
4. 2.とは違うエラーでForm1.csのデザイナーが開けない
5. 32bit/64bitの違いか？Debugビルド種別の変更方法は....

とぐるぐるやっております｡｢これが噂に名高いYak Shavingなのかなぁ｣と妙な感慨を受けていたり（笑）

目指せ今年中のPull Request!! 今後もよろしくお願いいたします｡
