### ISSUE TITLE
終了時に例外が発生し終了できなくなる

### ISSUE THREAD

**Issue by hide92795** [hibara/MarkDownSharpEditor#8]
終了時にSystem.ArgumentExceptionが発生しタスクマネージャーから強制終了させるしか終了できなくなりました。
ｘボタン or ファイルメニューの終了　→　例外発生　→　終了　と押しても例外画面が消えるだけでした。
また、特定のファイルのみで100％再発します。
必要でしたらそのファイルをお送りします。

使用しているバージョンは1.1.4.0です

以下例外内容です。

Just-In-Time (JIT) デバッグを呼び出すための詳細については、
ダイアログ ボックスではなく、このメッセージの最後を参照してください。

*************\* 例外テキスト **************
System.ArgumentException: 配列のオフセットおよび長さが範囲を超えているか、カウンターがソース コレクションのインデックスから最後までの要素の数より大きい値です。
   場所 System.Collections.ArrayList.RemoveRange(Int32 index, Int32 count)
   場所 MarkDownSharpEditor.AppSettings.OptimizeHistoryData()
   場所 MarkDownSharpEditor.AppSettings.SaveToXMLFile()
   場所 MarkDownSharpEditor.Form1.Form1_FormClosing(Object sender, FormClosingEventArgs e)
   場所 System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   場所 System.Windows.Forms.Form.WmClose(Message& m)
   場所 System.Windows.Forms.Form.WndProc(Message& m)
   場所 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   場所 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   場所 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* 読み込まれたアセンブリ **************
mscorlib
    アセンブリ バージョン: 4.0.0.0
    Win32 バージョン: 4.0.30319.17379 built by: FXBETAREL
##     コードベース: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

MarkDownSharpEditor
    アセンブリ バージョン: 1.1.4.0
    Win32 バージョン: 1.1.4.0
##     コードベース: file:///C:/Program%20Files%20(x86)/MarkDownSharpEditor/MarkDownSharpEditor.exe

System.Windows.Forms
    アセンブリ バージョン: 4.0.0.0
    Win32 バージョン: 4.0.30319.17451 built by: FXBETAGDR
##     コードベース: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System.Drawing
    アセンブリ バージョン: 4.0.0.0
    Win32 バージョン: 4.0.30319.17379 built by: FXBETAREL
##     コードベース: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System
    アセンブリ バージョン: 4.0.0.0
    Win32 バージョン: 4.0.30319.17379 built by: FXBETAREL
##     コードベース: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

mscorlib.resources
    アセンブリ バージョン: 4.0.0.0
    Win32 バージョン: 4.0.30319.17379 built by: FXBETAREL
##     コードベース: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ja_b77a5c561934e089/mscorlib.resources.dll

System.Windows.Forms.resources
    アセンブリ バージョン: 4.0.0.0
    Win32 バージョン: 4.0.30319.17379 built by: FXBETAREL
##     コードベース: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ja_b77a5c561934e089/System.Windows.Forms.resources.dll

System.Xml
    アセンブリ バージョン: 4.0.0.0
    Win32 バージョン: 4.0.30319.17379 built by: FXBETAREL
##     コードベース: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

System.Configuration
    アセンブリ バージョン: 4.0.0.0
    Win32 バージョン: 4.0.30319.17379 built by: FXBETAREL
##     コードベース: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

Microsoft.GeneratedCode
    アセンブリ バージョン: 1.0.0.0
    Win32 バージョン: 4.0.30319.17379 built by: FXBETAREL
##     コードベース: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

System.Core
    アセンブリ バージョン: 4.0.0.0
    Win32 バージョン: 4.0.30319.17379 built by: FXBETAREL
##     コードベース: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

Microsoft.mshtml
    アセンブリ バージョン: 7.0.3300.0
    Win32 バージョン: 7.0.3300.0
##     コードベース: file:///C:/Windows/assembly/GAC/Microsoft.mshtml/7.0.3300.0__b03f5f7f11d50a3a/Microsoft.mshtml.dll

*************\* JIT デバッグ **************
Just-In-Time (JIT) デバッグを有効にするには、このアプリケーション、
またはコンピューター (machine.config) の構成ファイルの jitDebugging 
値を system.windows.forms セクションで設定しなければなりません。
アプリケーションはまた、デバッグを有効にしてコンパイルされなければ
なりません。

例:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

JIT デバッグが有効なときは、このダイアログ ボックスで処理するよりも、
ハンドルされていない例外はすべてコンピューターに登録された
JIT デバッガーに設定されなければなりません。

**Comment by hibara** [comment]
ご報告ありがごとうございます。現象を確認しました。

MarkDown#Editorでは、過去に編集したmdファイルと、cssのセットを履歴として20保存しているのですが、それを超えたときに、古いものから削除していく、という処理で想定外の範囲の削除処理を行ってしまっていたようです・・・

次版では修正され、対応予定です。
