### ISSUE TITLE
置換機能がうまく機能しない

### ISSUE THREAD

**Issue by masa36** [hibara/MarkDownSharpEditor#9]
こんにちは、プレビュー付きで便利なソフトですね。
置換機能がうまくはたらかないので、将来バージョンへ向けて報告させてもらいます。
Version 1.1.4.0, Windows 7 64bit SP1 で確認しました。
よろしくお願いします。
#### test
- test_string_a_go_go
- test_string_a_go_go

expected to display `test_string_a_go_go`

のような内容に対して、_ を _ に置換したいと思って

![img000](https://f.cloud.github.com/assets/3655468/178996/6d9b8c98-7bdb-11e2-9dba-d13e1249daca.jpg)

[すべてを置換する] を実行すると、以下のように置換処理が延々と続いてしまいます。（\ がひたすら増えるように表示され、止めるにはタスクマネージャでプロセスを終了するしかなくなる）

![img001](https://f.cloud.github.com/assets/3655468/178997/6deeccc8-7bdb-11e2-8cfa-2c745e52d2f7.jpg)

**Comment by alg0002** [comment]
※Pull Requestだと改行コード変換設定のせいか変更行が大量になってしまうので、コメントで。

``` diff
@@ -2980,6 +2980,7 @@ private void cmdReplaceAll_Click(object sender, EventArgs e)
                {
                    richTextBox1.SelectedText = textBoxReplace.Text;
                    ReplaceCount++;
+                   CurrentPos = StartPos + textBoxReplace.Text.Length;
                }
            }

```

こんな感じの変更で、回避できるのではないでしょうか。

**Comment by hibara** [comment]
ご報告ありがとうございます。現象を確認しました・・・
どうにもこうにも、へっぽこバグでございました。。。。お恥ずかしい。

alg0002さん、いつもフォローありがとうございます。
どんぴしゃでした！　たいへん助かります！

次版で修正予定です。
